name = "chbwl-gateway-api"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "chbwl-gateway-api"

[env.staging]
name = "chbwl-gateway-api-staging"

[[routes]]
pattern = "api.yourdomain.com/*"
zone_name = "yourdomain.com"
